### ISSUE TITLE
Landfill was shut down

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/lyo-adaptor-bugzilla#12]
We need to switch to an alternative Bugzilla install: https://groups.google.com/forum/#!searchin/mozilla.support.bugzilla/landfill|sort:date/mozilla.support.bugzilla/mM3LiXWcq-A/4KgRcZluBQAJ

I found a relatively recent docker image: https://hub.docker.com/r/chardek/bugzilla/dockerfile

**Comment by jamsden** [comment]
Isn't it relatively easy and free for anyone to create a GitHub repo for 
testing purposes and delete it when they are done? I've done this a number 
of times with no problem.


Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by berezovskyi** [comment]
This is not about Git repos. Instead, the Bugzilla OSLC Adaptor needs a Bugzilla installation to be online and accessible over HTTP. Before we relied on a test installation managed by Mozilla, affectionately called "Bugzilla Landfill". They took it down. Thus, the setup of the adaptor now requires an installation of an Apache Server, Perl, and MySQL plus the Bugzilla itself.

**Comment by berezovskyi** [comment]
I have fixed the docker build in https://hub.docker.com/r/smarx008/bugzilla-dev-lyo

**Comment by berezovskyi** [comment]
Fixed in https://github.com/OSLC/lyo-adaptor-bugzilla/commit/5f2e2bbb5ee87215a8540279f6584f36ee5685fc

<img width="1456" alt="Screenshot 2020-12-06 at 16 39 40" src="https://user-images.githubusercontent.com/64734/101284730-c065d300-37e1-11eb-94e2-f6d664220c52.png">

<img width="1456" alt="Screenshot 2020-12-06 at 16 39 36" src="https://user-images.githubusercontent.com/64734/101284737-c52a8700-37e1-11eb-9595-fda86011801a.png">
